import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { WebsiteSeoSyncService } from '../../../../services/website-seo-sync.service';
interface Brand {
  name: string;
  devices: string[];
}

@Component({
  selector: 'app-nfc-compatibility',
  templateUrl: './nfc-compatibility.component.html',
  styleUrls: ['./nfc-compatibility.component.scss'],
  imports : [CommonModule,FormsModule,ReactiveFormsModule]
})


export class NfcCompatibilityComponent  implements OnInit {

openedBrand: string | null = null;

brands: Brand[] = [
  {
    name: 'Apple',
   devices : [
  'iPhone 15',
  'iPhone 15 Pro Max',
  'iPhone 15 Plus',
  'iPhone 13',
  'iPhone 14',
  'iPhone 16',
  'iPhone XR2',
  'iPhone 12',
  'iPhone 16 Pro Max',
  'iPhone 16 Pro',
  'iPhone 11',
  'iPhone 15 (256GB)',
  'iPhone 18 Pro Max',
  'iPhone 9',
  'iPhone 14 Plus',
  'iPhone 15 Plus (256GB)',
  'iPhone 14 Mini',
  'iPhone 15 Pro',
  'iPhone 14 (256GB)',
  'iPhone 15 Pro Max (512GB)',
  'iPhone 15 (512GB)',
  'iPhone SE 3 2022',
  'iPhone 12 (128GB)',
  'iPhone 15 Pro Max (1TB)',
  'iPhone 13 Pro Max (1TB)',
  'iPhone 12 (256GB)',
  'iPhone 15 Pro (256GB)',
  'iPhone XR',
  'iPhone 13 Pro (1TB)',
  'iPhone 15 Max',
  'iPhone 14 (512GB)',
  'iPhone 15 Ultra',
  'iPhone 17',
  'iPhone 14 Plus (256GB)',
  'iPhone SE 2020',
  'iPhone 15 Pro (1TB)',
  'iPhone 6 Plus (64GB)',
  'iPhone 17 Plus',
  'iPhone 8 Plus',
  'iPhone 14 Plus (512GB)',
  'iPhone 13 Pro Max (512GB)',
  'iPhone 8 (256GB)',
  'iPhone 16 Plus',
  'iPhone 15 Pro (512GB)',
  'iPhone 17 Pro Max',
  'iPhone 14 Max',
  'iPhone 15 Plus (512GB)',
  'iPhone XR 2019',
  'iPhone 16 Ultra',
  'iPhone 8 Plus (256GB)',
  'iPhone 6s (32GB)',
  'iPhone 12 Pro',
  'iPhone SE 3 2022 (128GB)',
  'iPhone 12 Pro Max (256GB)',
  'iPhone 11 Pro Max',
  'iPhone 13 (512GB)',
  'iPhone 13 (256GB)',
  'iPhone 12 Pro Max',
  'iPhone 17 Pro',
  'iPhone SE 4',
  'iPhone SE Plus 5G',
  'iPhone 14 Pro (256GB)',
  'iPhone 13 Pro Max',
  'iPhone 11 (128GB)',
  'iPhone 13 Mini',
  'iPhone 12 Mini',
  'iPhone 12 Pro (256GB)',
  'iPhone 13 Pro',
  'iPhone 14 Pro (1TB)',
  'iPhone 11 Pro',
  'iPhone 14 Pro',
  'iPhone 14 Pro Max (256GB)',
  'iPhone 14 Pro Max (512GB)',
  'iPhone 7 Plus',
  'iPhone XS Max (256GB)',
  'iPhone 13 Pro (256GB)',
  'iPhone 8 (128GB)',
  'iPhone 8 Plus (128GB)',
  'iPhone X',
  'iPhone 6s Plus (64GB)',
  'iPhone 6 (128GB)',
  'iPhone 12 Mini (256GB)',
  'iPhone 6s Plus (32GB)',
  'iPhone 7',
  'iPhone 13 Mini (512GB)',
  'iPhone 13 Pro Max (256GB)',
  'iPhone SE Plus (2020)',
  'iPhone SE',
  'iPhone 6s Plus (128GB)',
  'iPhone 14 Pro Max (1TB)',
  'iPhone 6 Plus',
  'iPhone SE (32GB)',
  'iPhone 11 Pro (512GB)',
  'iPhone 11 Pro Max (256GB)',
  'iPhone 6',
  'iPhone SE (64GB)',
  'iPhone 6 (64GB)',
  'iPhone SE 2020 (128GB)',
  'iPhone XS (512GB)',
  'iPhone 6 Plus (128GB)',
  'iPhone 6 (32GB)',
  'iPhone SE (128GB)',
  'iPhone 11 Pro Max (512GB)',
  'iPhone 6s (128GB)',
  'iPhone 7 (128GB)',
  'iPhone 11 (256GB)',
  'iPhone SE 2020 (256GB)',
  'iPhone 6s Plus',
  'iPhone XS Max',
  'iPhone 7 (256GB)',
  'iPhone 14 Pro (512GB)',
  'iPhone 7 Plus (256GB)',
  'iPhone 8',
  'iPhone SE 3 2022 (256GB)',
  'iPhone 11 Pro (256GB)',
  'iPhone 13 Pro (512GB)',
  'iPhone XS Max (512GB)',
  'iPhone XS (256GB)',
  'iPhone SE 2021',
  'iPhone 13 Mini (256GB)',
  'iPhone XS',
  'iPhone X (256GB)',
  'iPhone XR (128GB)',
  'iPhone 6s (64GB)',
  'iPhone 6s',
  'iPhone 7 Plus (128GB)',
  'iPhone 14 Pro Max',
  'iPhone 12 Pro Max (512GB)',
  'iPhone 12 Pro (512GB)',
  'iPhone 12 Mini (128GB)',
  'iPhone XR (256GB)'
]
  },

  {
    name: 'Essential',
    devices: [
      'Essential PH-1'
    ]
  },

  {
    name: 'Poco',
    devices: [
      'Poco X3 GT',
      'Poco F3',
      'Poco F2 Pro'
    ]
  },

  {
    name: 'Samsung',
  devices : [
  'Samsung Galaxy S24 Ultra',
  'Samsung Galaxy S24 5G',
  'Samsung Galaxy M34 5G',
  'Samsung Galaxy S21 FE (Snapdragon)',
  'Samsung Galaxy S21 FE 5G',
  'Samsung Galaxy S24 Ultra (12GB RAM + 512GB)',
  'Samsung Galaxy S23 5G',
  'Samsung Galaxy F54',
  'Samsung Galaxy A74 5G',
  'Samsung Galaxy A34 5G',
  'Samsung Galaxy M15',
  'Samsung Galaxy A55 5G',
  'Samsung Galaxy M34 5G (8GB RAM + 256GB)',
  'Samsung Galaxy S22 5G',
  'Samsung Galaxy S24 Plus',
  'Samsung Galaxy S23 (8GB RAM + 256GB)',
  'Samsung Galaxy S21 FE (Snapdragon + 8GB RAM + 128GB)',
  'Samsung Galaxy S22 Ultra 5G',
  'Samsung Galaxy F34 5G',
  'Samsung Galaxy S20 Ultra',
  'Samsung Galaxy S21 FE 5G',
  'Samsung Galaxy Z Fold 6',
  'Samsung Galaxy S20 Ultra',
  'Samsung Galaxy A25 5G',
  'Samsung Galaxy F15',
  'Samsung Galaxy M51',
  'Samsung Galaxy S24 Plus (12GB RAM + 512GB)',
  'Samsung Galaxy A34 5G (8GB RAM + 256GB)',
  'Samsung Galaxy F55 5G',
  'Samsung Galaxy A35 5G',
  'Samsung Galaxy M16',
  'Samsung Galaxy M34 5G (8GB RAM + 128GB)',
  'Samsung Galaxy Z Fold 5',
  'Samsung Galaxy S23 (8GB RAM + 256GB)',
  'Samsung Galaxy S23 Ultra (12GB RAM + 512GB)',
  'Samsung Galaxy Z Flip 3',
  'Samsung Galaxy S24 (8GB RAM + 512GB)',
  'Samsung Galaxy S24 Ultra (12GB RAM + 1TB)',
  'Samsung Galaxy M35',
  'Samsung Galaxy A25 5G (8GB RAM + 256GB)',
  'Samsung Galaxy A75 5G',
  'Samsung Galaxy F34 5G (8GB RAM + 128GB)',
  'Samsung Galaxy S22 FE 5G',
  'Samsung Galaxy S24 FE',
  'Samsung Galaxy F34 5G',
  'Samsung Galaxy Note 10 Plus',
  'Samsung Galaxy S24 (8GB RAM + 128GB)',
  'Samsung Galaxy Z Flip 5',
  'Samsung Galaxy Z Flip 4 5G',
  'Samsung Galaxy S22 5G (8GB RAM + 256GB)',
  'Samsung Galaxy A25',
  'Samsung Galaxy S21 Ultra',
  'Samsung Galaxy S20',
  'Samsung Galaxy M33 5G',
  'Samsung Galaxy S20 Ultra 5G',
  'Samsung Galaxy A76',
  'Samsung Galaxy M52 5G (8GB RAM + 128GB)',
  'Samsung Galaxy S23 FE 5G (8GB RAM + 256GB)',
  'Samsung Galaxy S21 Plus',
  'Samsung Galaxy S23 Plus (8GB RAM + 512GB)',
  'Samsung Galaxy A33 5G',
  'Samsung Galaxy A53 (8GB RAM + 256GB)',
  'Samsung Galaxy Z Fold 5 (12GB RAM + 512GB)',
  'Samsung Galaxy F64 5G',
  'Samsung Galaxy A82 5G',
  'Samsung Galaxy F25 5G',
  'Samsung Galaxy S21 5G (8GB RAM + 256GB)',
  'Samsung Galaxy S20 5G',
  'Samsung Galaxy M44 5G',
  'Samsung Galaxy Note 20 Ultra 4G',
  'Samsung Galaxy Z Flip 5 (8GB RAM + 512GB)',
  'Samsung Galaxy Z Flip 6',
  'Samsung Galaxy Z Fold 5 (12GB RAM + 1TB)',
  'Samsung Galaxy S22 Ultra 5G (12GB RAM + 512GB)',
  'Samsung Galaxy Z Flip 4 (8GB RAM + 256GB)',
  'Samsung Galaxy S22 Ultra 5G (8GB RAM + 128GB)',
  'Samsung Galaxy Note 30 5G',
  'Samsung Galaxy A90 5G',
  'Samsung Galaxy A34 5G (8GB RAM + 128GB)',
  'Samsung W22 5G',
  'Samsung Galaxy Fold 5G',
  'Samsung Galaxy A53 (8GB RAM + 256GB)',
  'Samsung Galaxy Z Fold 3',
  'Samsung Galaxy A52 5G',
  'Samsung Galaxy S20 FE 5G',
  'Samsung Galaxy A34 5G (8GB RAM + 128GB)',
  'Samsung Galaxy F63',
  'Samsung Galaxy S23 Plus (8GB RAM + 512GB)',
  'Samsung Galaxy Bloom',
  'Samsung Galaxy Note 10 5G',
  'Samsung Galaxy F44',
  'Samsung Galaxy F23 5G',
  'Samsung Galaxy Xcover Pro 2',
  'Samsung Galaxy S25',
  'Samsung Galaxy A56',
  'Samsung Galaxy A24 5G',
  'Samsung Galaxy M54 5G',
  'Samsung Galaxy F23 5G (6GB RAM + 128GB)',
  'Samsung Galaxy A53 5G (8GB RAM + 128GB)',
  'Samsung Galaxy S20 Plus 5G',
  'Samsung Galaxy A33 5G (8GB RAM + 128GB)',
  'Samsung Galaxy S20 FE',
  'Samsung W23 Flip',
  'Samsung Galaxy M62',
  'Samsung Galaxy Note 10 Plus 5G',
  'Samsung Galaxy Z Flip 3 5G (8GB RAM + 256GB)',
  'Samsung Galaxy M34 5G (8GB RAM + 128GB)',
  'Samsung Galaxy F14',
  'Samsung Galaxy A24',
  'Samsung Galaxy M63',
  'Samsung Galaxy A21',
  'Samsung Galaxy Note 30 Ultra 5G',
  'Samsung Galaxy F34 5G (8GB RAM + 128GB)',
  'Samsung Galaxy M52 5G',
  'Samsung Galaxy A83 5G',
  'Samsung Galaxy S21',
  'Samsung Galaxy Z Fold 4 (12GB RAM + 512GB)',
  'Samsung Galaxy Z Flip 4 (8GB RAM + 256GB)',
  'Samsung Galaxy A9 Pro (2019)',
  'Samsung Galaxy A13 5G',
  'Samsung Galaxy S22 Plus 5G (8GB RAM + 256GB)',
  'Samsung W24',
  'Samsung Galaxy A50s (6GB RAM + 128GB)',
  'Samsung Galaxy Z Flip 4 (8GB RAM + 512GB)',
  'Samsung Galaxy A54 5G (8GB RAM + 256GB)',
  'Samsung Galaxy A32 5G',
  'Samsung Galaxy Buddy 2',
  'Samsung W23',
  'Samsung Galaxy S21 Plus 5G (8GB RAM + 256GB)',
  'Samsung Galaxy M33 5G (8GB RAM + 128GB)',
  'Samsung Galaxy S21 Ultra 5G (12GB RAM + 128GB)',
  'Samsung Galaxy S10 5G',
  'Samsung Galaxy Z Fold 4',
  'Samsung Galaxy Note 20 5G',
  'Samsung Galaxy S21 FE 5G (8GB RAM + 256GB)',
  'Samsung Galaxy S23 Plus',
  'Samsung Galaxy A33 5G',
  'Samsung Galaxy F62 (8GB RAM + 128GB)',
  'Samsung Galaxy S23 Plus (8GB RAM + 512GB)',
  'Samsung Galaxy S10 Plus',
  'Samsung Galaxy S9',
  'Samsung Galaxy A52s 5G',
  'Samsung Galaxy S10',
  'Samsung Galaxy Note 10 Plus (12GB RAM + 512GB)',
  'Samsung Galaxy A73 5G (8GB RAM + 256GB)',
  'Samsung Galaxy Note 9',
  'Samsung Galaxy S22 Ultra 5G (12GB RAM + 1TB)',
  'Samsung Galaxy A31',
  'Samsung Galaxy S10e',
  'Samsung Galaxy A52s 5G (8GB RAM + 128GB)',
  'Samsung Galaxy S20 FE (256GB)',
  'Samsung Galaxy Z Fold 2 5G',
  'Samsung Galaxy J7 Pro',
  'Samsung Galaxy S10 Lite',
  'Samsung Galaxy S4',
  'Samsung Galaxy F62',
  'Samsung Galaxy A60',
  'Samsung Galaxy Note 2 (N7100)',
  'Samsung Galaxy Note 10 Lite (8GB RAM + 128GB)',
  'Samsung Galaxy Note 9 (8GB RAM + 512GB)',
  'Samsung Galaxy S7 Edge',
  'Samsung Galaxy Express',
  'Samsung Galaxy A5 (2016)',
  'Samsung Galaxy A7 (2016)',
  'Samsung Galaxy A7',
  'Samsung Galaxy Alpha',
  'Samsung Galaxy S4 Zoom C1010',
  'Samsung Galaxy Note 7',
  'Samsung Galaxy S8 Active',
  'Samsung Galaxy S5',
  'Samsung Galaxy S6 Edge (128GB)',
  'Samsung Galaxy J7 (2016)',
  'Samsung Galaxy A9 (2018)',
  'Samsung Galaxy Note 3 N9005 (3G+LTE)',
  'Samsung Galaxy S21 4G',
  'Samsung Galaxy S20 Lite',
  'Samsung Galaxy Note 6',
  'Samsung Galaxy S3 I9300, S III (32GB)',
  'Samsung Galaxy J5 (2017)',
  'Samsung Galaxy S9 Plus',
  'Samsung Galaxy S6 Edge (64GB)',
  'Samsung Galaxy A3',
  'Samsung Galaxy A51 5G UW',
  'Samsung Galaxy S20 5G UW',
  'Samsung Galaxy Z Fold 3 5G (12GB RAM + 512GB)',
  'Samsung Galaxy M60',
  'Samsung Galaxy S6 Edge Plus',
  'Samsung Galaxy S8',
  'Samsung Galaxy A7 (Single Sim)',
  'Samsung Galaxy Note 5 (64GB)',
  'Samsung Galaxy A70e',
  'Samsung Galaxy Note 5 Dual Sim (64GB)',
  'Samsung Galaxy A3 Duos',
  'Samsung Galaxy Z Flip 5G',
  'Samsung Galaxy S3 Mini (I8190)',
  'Samsung Galaxy S5 Neo',
  'Samsung Galaxy A3 (2016)',
  'Samsung Galaxy Note 10 Plus Star Wars Edition',
  'Samsung Galaxy S9 (256GB)',
  'Samsung Galaxy J3 Pro',
  'Samsung Galaxy S10 Lite (8GB RAM + 512GB)',
  'Samsung Wave Y S5380',
  'Samsung Galaxy S6 (128GB)',
  'Samsung Galaxy Z Fold 3',
  'Samsung Galaxy J5 Pro',
  'Samsung Galaxy S9 (128GB)',
  'Samsung Galaxy F13 (4GB RAM + 128GB)',
  'Samsung Galaxy A6s',
  'Samsung Galaxy Fold',
  'Samsung Galaxy A73 5G',
  'Samsung Galaxy C7 (2017)',
  'Samsung Galaxy A5 Duos',
  'Samsung Galaxy S6',
  'Samsung Galaxy S6 Active',
  'Samsung Galaxy S23 Ultra (12GB RAM + 1TB)',
  'Samsung Galaxy S23 FE 5G (Snapdragon)',
  'Samsung Galaxy Z Flip 4 Bespoke Edition',
  'Samsung Galaxy Xcover 5',
  'Samsung Galaxy C5',
  'Samsung Galaxy S5 (32GB)',
  'Samsung Galaxy A90',
  'Samsung Galaxy A5',
  'Samsung Galaxy Xcover 3',
  'Samsung Galaxy Mega 2',
  'Samsung Galaxy Xcover 4s',
  'Samsung Galaxy C7',
  'Samsung Galaxy K zoom (S5 zoom)',
  'Samsung Galaxy A9 Star Lite',
  'Samsung Galaxy Nexus Prime I9250',
  'Samsung Galaxy Note 20 Ultra 5G',
  'Samsung Galaxy A8s',
  'Samsung Galaxy A6',
  'Samsung Galaxy J',
  'Samsung Z',
  'Samsung Galaxy A9 Pro',
  'Samsung Galaxy Quantum 2 5G',
  'Samsung Galaxy A70s',
  'Samsung Galaxy A80',
  'Samsung Galaxy M42 5G',
  'Samsung Galaxy A Quantum',
  'Samsung Galaxy Note FE',
  'Samsung Galaxy S5 Plus',
  'Samsung Galaxy A5 (2017)',
  'Samsung Google Nexus S I9023',
  'Samsung Galaxy Note 5 Dual Sim',
  'Samsung Galaxy S3 mini VE I8200',
  'Samsung I9502 Galaxy S4 Duos',
  'Samsung Galaxy A81',
  'Samsung Galaxy Core Plus',
  'Samsung Galaxy Fold Lite',
  'Samsung Galaxy S9 Plus (128GB)',
  'Samsung Galaxy S3 I9300, S III (16GB)',
  'Samsung W20 5G',
  'Samsung Galaxy Note 3 N9000',
  'Samsung Galaxy S9 Plus (256GB)',
  'Samsung Galaxy S5 Active',
  'Samsung Galaxy S7 Active',
  'Samsung Galaxy S5 Dual Sim',
  'Samsung Galaxy A50s',
  'Samsung Galaxy A8 (2018)',
  'Samsung Galaxy Ace 3 Duos S7272',
  'Samsung Galaxy Note 5',
  'Samsung Galaxy Note 10 Lite',
  'Samsung Galaxy S20 Plus',
  'Samsung Galaxy A7 (2017)',
  'Samsung Galaxy Z Flip 3 5G (8GB RAM + 256GB)',
  'Samsung Galaxy S10 Plus (12GB RAM + 1TB)',
  'Samsung Galaxy J5 (2016)',
  'Samsung Galaxy S5 Sport (For Sprint)',
  'Samsung Galaxy S5 mini',
  'Samsung Galaxy Note N7000',
  'Samsung Galaxy C9 Pro',
  'Samsung Galaxy S7',
  'Samsung Galaxy Z Fold 4 (12GB RAM + 1TB)',
  'Samsung Galaxy Core Prime 4G',
  'Samsung Galaxy A8 (2016)',
  'Samsung Galaxy S7 Edge (128GB)',
  'Samsung Galaxy A8 Plus (2018)',
  'Samsung Galaxy A9 Star',
  'Samsung Galaxy S4 Active I9295',
  'Samsung Galaxy M90',
  'Samsung Galaxy C5 Pro',
  'Samsung Galaxy S6 (64GB)',
  'Samsung Galaxy Mega 6.3 I9200 (8GB)',
  'Samsung Galaxy Core Lite LTE',
  'Samsung Galaxy A5 (2018)',
  'Samsung Galaxy Ace Style',
  'Samsung Galaxy S21 Ultra 5G (16GB RAM + 512GB)',
  'Samsung Galaxy S6 Edge',
  'Samsung I9230 Galaxy Golden',
  'Samsung Galaxy Mega 6.3 I9200 (16GB)',
  'Samsung Galaxy J7 (2017)',
  'Samsung Galaxy A8s (8GB RAM + 128GB)',
  'Samsung Galaxy Note 7R',
  'Samsung Galaxy S Light Luxury',
  'Samsung Galaxy J3 (2017)',
  'Samsung Galaxy S9 Active',
  'Samsung Galaxy XCover Pro',
  'Samsung Galaxy Ace 3 S7270',
  'Samsung Galaxy P30',
  'Samsung Galaxy Round G910S',
  'Samsung Galaxy S8 Plus',
  'Samsung Galaxy A91',
  'Samsung Galaxy J3',
  'Samsung Galaxy Note 8',
  'Samsung Galaxy M42 5G (8GB RAM + 128GB)',
  'Samsung Galaxy A6 (4GB RAM + 64GB)',
  'Samsung Galaxy S2 Plus I9105',
  'Samsung Galaxy A42',
  'Samsung Galaxy Note 3 Neo',
  'Samsung Galaxy J7 Plus',
  'Samsung Galaxy Feel',
  'Samsung Galaxy M51',
  'Samsung Galaxy Xcover 4',
  'Samsung Galaxy A3 (2017)',
  'Samsung Galaxy S11e',
  'Samsung Galaxy A9',
  'Samsung Galaxy C10',
  'Samsung Galaxy Core Advance',
  'Samsung Galaxy Express 2',
  'Samsung Galaxy M51 (8GB RAM + 128GB)',
  'Samsung Galaxy S10 Plus (8GB RAM + 512GB)',
  'Samsung Galaxy C7 Pro',
  'Samsung Galaxy S4 Mini Plus',
  'Samsung Galaxy S10 (8GB RAM + 512GB)',
  'Samsung Galaxy A9 (8GB RAM + 128GB)',
  'Samsung Galaxy Note Edge',
  'Samsung Galaxy Premier I9260',
  'Samsung W21 5G',
  'Samsung Galaxy A90s',
  'Samsung Galaxy Note 10',
  'Samsung Galaxy Note 4',
  'Samsung Galaxy Ace 2 I8160'
]
  },

  {
    name: 'One Plus',
 devices : [
  'OnePlus Nord CE 3 5G',
  'OnePlus 12R',
  'OnePlus 12',
  'OnePlus Nord 3 5G',
  'OnePlus 12R (16GB RAM + 256GB)',
  'OnePlus Nord 4 5G',
  'OnePlus Nord 3 5G (16GB RAM + 256GB)',
  'OnePlus 12 Pro',
  'OnePlus 11 5G',
  'OnePlus 13',
  'OnePlus 11R (16GB RAM + 256GB)',
  'OnePlus 12 (16GB RAM + 512GB)',
  'OnePlus 10 Pro 5G',
  'OnePlus Ace 3V',
  'OnePlus Nord 5',
  'OnePlus 13 Pro',
  'OnePlus Open 5G',
  'OnePlus 9R (12GB RAM + 256GB)',
  'OnePlus Nord N30 SE',
  'OnePlus Ace 2 Pro',
  'OnePlus 10T',
  'OnePlus Nord CE 3 (12GB RAM + 256GB)',
  'OnePlus V Flip',
  'OnePlus Ace Racing Edition 5G',
  'OnePlus 10 Pro 5G (12GB RAM + 256GB)',
  'OnePlus 10R 5G',
  'OnePlus 13R',
  'OnePlus Nord CE 4 5G',
  'OnePlus Nord N40 SE',
  'OnePlus Nord N30 5G',
  'OnePlus 6T',
  'OnePlus 10 Pro 5G (12GB RAM + 512GB)',
  'OnePlus Ace 5G',
  'OnePlus 10T (12GB RAM + 256GB)',
  'OnePlus 11 5G',
  'OnePlus Ace Pro',
  'OnePlus Nord 3T 5G',
  'OnePlus Nord 2 Lite 5G',
  'OnePlus 10RT 5G',
  'OnePlus Nord N200',
  'OnePlus 8T Plus 5G',
  'OnePlus Nord N300',
  'OnePlus Nord 3 5G (16GB RAM + 256GB)',
  'OnePlus Ace 3',
  'OnePlus 9',
  'OnePlus Nord 2T (12GB RAM + 256GB)',
  'OnePlus 9RT 5G (8GB RAM + 256GB)',
  'OnePlus 10 Ultra 5G',
  'OnePlus 10 Pro 5G (8GB RAM + 256GB)',
  'OnePlus 11R (16GB RAM + 256GB)',
  'OnePlus Nord N20 5G',
  'OnePlus 12T',
  'OnePlus 11R 5G (18GB RAM + 512GB)',
  'OnePlus 11 (16GB RAM + 256GB)',
  'OnePlus 10R 5G (12GB RAM + 256GB)',
  'OnePlus 10 Pro 5G (12GB RAM + 256GB)',
  'OnePlus Nord 2 5G (12GB RAM + 256GB)',
  'OnePlus Nord 2 5G',
  'OnePlus 6T',
  'OnePlus 10R 5G (150W)',
  'OnePlus 9',
  'OnePlus Nord CE 5G',
  'OnePlus 9 Pro (12GB RAM + 256GB)',
  'OnePlus 7',
  'OnePlus 10T (16GB RAM + 256GB)',
  'OnePlus 11 5G Marble Odyssey',
  'OnePlus Nord (12GB RAM + 256GB)',
  'OnePlus Nord 2T 5G',
  'OnePlus 7 (8GB RAM + 256GB)',
  'OnePlus 7T',
  'OnePlus 4',
  'OnePlus 5T (6GB RAM + 64GB)',
  'OnePlus 8 (8GB RAM + 128GB)',
  'OnePlus 7T Pro',
  'OnePlus 6T (8GB RAM + 128GB)',
  'OnePlus 7T (8GB RAM + 256GB)',
  'OnePlus 9 Pro',
  'OnePlus 5T',
  'OnePlus 5',
  'OnePlus 6 (8GB RAM + 256GB)',
  'OnePlus 3T (128GB)',
  'OnePlus 5 (6GB RAM+64GB)',
  'OnePlus 9R 5G',
  'OnePlus 8',
  'OnePlus Nord N10',
  'OnePlus 7 Pro (12GB RAM + 256GB)',
  'OnePlus 3T',
  'OnePlus 9R (12GB RAM + 256GB)',
  'OnePlus 8 (12GB RAM + 256GB)',
  'OnePlus Nord 5G',
  'OnePlus 6T (8GB RAM + 256GB)',
  'OnePlus 8 Pro (12GB RAM + 256GB)',
  'OnePlus 9RT 5G',
  'OnePlus 8 Lite',
  'OnePlus 10 5G',
  'OnePlus 9 Lite',
  'OnePlus 6',
  'OnePlus One',
  'OnePlus 3',
  'OnePlus 6 (8GB RAM + 128GB)',
  'OnePlus 7 Pro (8GB RAM + 256GB)',
  'OnePlus 7 Pro',
  'OnePlus 6',
  'OnePlus Nord (8GB RAM + 128GB)',
  'OnePlus 9E',
  'OnePlus 3',
  'OnePlus One',
  'OnePlus 9RT 5G (12GB RAM + 256GB)',
  'OnePlus 9 Pro (12GB RAM + 256GB)',
  'OnePlus 8 Pro',
  'OnePlus 7 Pro (8GB RAM + 256GB)',
  'OnePlus 6 (8GB RAM + 256GB)',
  'OnePlus Nord CE 5G (12GB RAM + 256GB)',
  'OnePlus One (16GB)',
  'OnePlus 7T'
]
  },

  {
    name: 'Nokia',
    devices: [
      'Nokia Lumia 930',
      'Nokia Lumia 920',
      'Nokia 9',
      'Nokia 8.1',
      'Nokia 8',
      'Nokia 8 Sirocco',
      'Nokia 7 Plus',
      'Nokia 7',
      'Nokia 6.1',
      'Nokia 6',
      'Nokia 5.1',
      'Nokia 5',
      'Nokia 4.2',
      'Nokia 3.1',
      'Nokia 3'
    ]
  },

  {
    name: 'Nothing',
    devices: [
      'Nothing Phone (2)',
      'Nothing Phone (1)'
    ]
  },

  {
    name: 'Motorola',
    devices:  [
  'Motorola Edge 40 Neo',
  'Motorola Edge 40 5G',
  'Motorola Edge 30 Ultra (12GB RAM + 256GB)',
  'Motorola Edge 40 Neo (12GB RAM + 256GB)',
  'Motorola Moto Edge 50 Neo',
  'Motorola Moto G84 5G',
  'Motorola Moto G73',
  'Motorola Razr 40',
  'Motorola Edge 50 Pro',
  'Motorola Moto G82 5G',
  'Motorola Moto G74',
  'Motorola Edge 50',
  'Motorola Edge 30 Fusion 5G',
  'Motorola Moto G82 (8GB RAM + 128GB)',
  'Motorola Moto G71 5G',
  'Motorola Razr 50 Ultra',
  'Motorola Edge 30 5G',
  'Motorola Moto G23',
  'Motorola Moto X30 Pro',
  'Motorola Razr Plus 2024',
  'Motorola Edge 40 Pro 5G',
  'Motorola Razr 40 Ultra 2024',
  'Motorola Edge S',
  'Motorola Moto Edge 30 Neo',
  'Motorola Moto G91 5G',
  'Motorola Moto X40',
  'Motorola Edge Plus',
  'Motorola Moto G73',
  'Motorola Moto G91 5G',
  'Motorola Razr Plus 2023',
  'Motorola Moto X60',
  'Motorola Edge Plus',
  'Motorola Moto G Stylus 5G 2024',
  'Motorola Razr Lite',
  'Motorola Moto G Stylus 5G 2023',
  'Motorola Moto G72',
  'Motorola Moto G Stylus 5G 2022',
  'Motorola Defy',
  'Motorola Moto G53',
  'Motorola Frontier',
  'Motorola Moto G50 5G',
  'Motorola Edge 40 Fusion',
  'Motorola Rizr Rollable',
  'Motorola Razr 2023',
  'Motorola Razr 40 Ultra',
  'Motorola Edge 2021',
  'Motorola Nio',
  'Motorola Edge 20 5G',
  'Motorola Moto G 5G',
  'Motorola Edge 20 Pro 5G',
  'Motorola Edge X30 Champion Edition 5G',
  'Motorola Moto Edge X30 5G',
  'Motorola Razr 2019',
  'Motorola Razr 50',
  'Motorola Moto Edge X30 Pro',
  'Motorola Frontier 22 5G',
  'Motorola Edge 2023',
  'Motorola Moto Edge 5G 2022',
  'Motorola Moto One Vision',
  'Motorola Moto Edge X30 5G (12GB RAM + 256GB)',
  'Motorola Razr 3 5G',
  'Motorola Moto G53s',
  'Motorola Moto X50',
  'Motorola Edge 50 Fusion',
  'Motorola ThinkPhone',
  'Motorola Edge 30 Ultra',
  'Motorola Edge 20 Fusion 5G (8GB RAM + 128GB)',
  'Motorola Edge Lite',
  'Motorola Moto Z4',
  'Motorola Moto Z4 Play',
  'Motorola Moto X5',
  'Motorola Moto G100',
  'Motorola Razr 5G',
  'Motorola Moto Z3 Play',
  'Motorola Moto G50',
  'Motorola Moto G30 (6GB RAM + 128GB)',
  'Motorola One 5G Ace',
  'Motorola Moto G60S',
  'Motorola Moto X Play (16GB)',
  'Motorola Edge S Pioneer Edition',
  'Motorola Moto Z4 Play',
  'Motorola Moto Maxx',
  'Motorola One 5G 2020',
  'Motorola DROID Maxx 2',
  'Motorola Moto P30 (6GB RAM + 128GB)',
  'Motorola P30 Note (6GB RAM + 64GB)',
  'Motorola Moto G 5G Plus',
  'Motorola P40 Power',
  'Motorola Moto G7 Plus',
  'Motorola Moto Z Force',
  'Motorola Moto G200',
  'Motorola Moto P40 Play',
  'Motorola One Hyper',
  'Motorola P50',
  'Motorola Moto Bounce',
  'Motorola DROID Turbo',
  'Motorola Edge 20 Lite',
  'Motorola Moto X30 Pro (12GB RAM + 256GB)',
  'Motorola Edge S Pro',
  'Motorola Moto G Pro',
  'Motorola One 5G UW',
  'Motorola One Pro',
  'Motorola DROID Turbo 2',
  'Motorola Moto X (3rd Gen)',
  'Motorola Moto Z4 Force',
  'Motorola RAZR i XT890',
  'Motorola Razr 2022',
  'Motorola One Mid',
  'Motorola One Zoom',
  'Motorola P30',
  'Motorola Moto X Play',
  'Motorola P30 Play',
  'Motorola P30 Note',
  'Motorola Moto X Style (32GB)',
  'Motorola Edge 20 Fusion 5G',
  'Motorola Moto Edge X 5G',
  'Motorola Defy 2021',
  'Motorola Moto G9 Plus',
  'Motorola Edge'
]
  },

  {
    name: 'LG',
    devices: [
      'LG Q92',
      'LG G8 ThinQ',
      'LG Q8',
      'LG G7 ThinQ',
      'LG Q7',
      'LG Q Stylus',
      'LG Q6 Plus',
      'LG Q6',
      'LG G6',
      'LG V40 ThinQ',
      'LG V35 ThinQ',
      'LG V30 ThinQ',
      'LG V30',
      'LG V20',
      'LG V10',
      'LG Nexus 5X',
      'LG G5',
      'LG G4',
      'LG G3'
    ]
  },

  {
    name: 'Google',
    devices: [
      'Google Pixel 8 Pro',
      'Google Pixel 8',
      'Google Pixel 7 Pro',
      'Google Pixel 7a',
      'Google Pixel 7',
      'Google Pixel 6',
      'Google Pixel 6a',
      'Google Nexus 6P',
      'Google Nexus 5X',
      'Google Pixel 4A',
      'Google Nexus 4',
      'Google Pixel 3A',
      'Google Pixel 3',
      'Google Pixel 3XL',
      'Google Pixel 2XL',
      'Google Pixel 2',
      'Google Pixel XL',
      'Google Pixel'
    ]
  },

  {
    name: 'Sony',
    devices: [
      'Sony Xperia M2',
      'Sony Xperia L2',
      'Sony Xperia E3',
      'Sony Xperia T2',
      'Sony Xperia Z5',
      'Sony Xperia Z2',
      'Sony Xperia XA1 Plus',
      'Sony Xperia SP',
      'Sony Xperia Z3+',
      'Sony Xperia ZR',
      'Sony Xperia XA',
      'Sony Xperia T3',
      'Sony Xperia XZ',
      'Sony Xperia XA1 Ultra',
      'Sony Xperia XA1 Dual',
      'Sony Xperia XZ1',
      'Sony Xperia C5',
      'Sony Xperia Z1',
      'Sony Xperia XA1'
    ]
  },

  {
    name: 'Asus',
    devices: [
      'Asus ROG Phone'
    ]
  },

  {
    name: 'Honor',
    devices: [
      'Honor 8 Pro',
      'Honor V10',
      'Honor View 20',
      'Honor 8'
    ]
  },

  {
    name: 'HTC',
    devices: [
      'HTC One M9 Plus',
      'HTC One E9+',
      'HTC One ME',
      'HTC 10 Lifestyle',
      'HTC Desire Eye',
      'HTC One E8',
      'HTC Desire 10 Pro',
      'HTC U11 Plus',
      'HTC 10 Evo',
      'HTC U Ultra',
      'HTC Desire 20 Plus',
      'HTC One A9'
    ]
  },

  {
    name: 'OPPO',
   devices : [
  'OPPO Reno 11',
  'OPPO Reno 11 Pro',
  'OPPO Reno 11 (8GB RAM + 256GB)',
  'Oppo Find X7 Ultra',
  'OPPO Reno 12',
  'Oppo Find X6 Pro',
  'Oppo Reno 8T',
  'Oppo Find X7 Pro 5G',
  'OPPO F25',
  'Oppo Reno 10 Pro Plus',
  'OPPO K11 5G',
  'OPPO Reno 8 Pro 5G',
  'OPPO Reno 10 Pro',
  'Oppo Reno 11F 5G',
  'Oppo K12',
  'OPPO Reno 9 Pro 5G',
  'OPPO Reno8 5G',
  'Oppo A98',
  'OPPO Reno7 Pro 5G',
  'Oppo Find X6',
  'Oppo Find X7 5G',
  'Oppo A78 4G',
  'OPPO Reno 9 Pro Plus',
  'OPPO Reno7 Pro 5G (12GB RAM + 512 GB)',
  'OPPO Find N4 Flip',
  'Oppo Reno 9T',
  'OPPO Find X2 Pro',
  'OPPO Reno 8 Pro 5G',
  'OPPO Reno7 5G',
  'OPPO Reno 9 5G',
  'OPPO Reno 8 4G',
  'Oppo Find N3',
  'OPPO Find X2',
  'OPPO Find N2 Flip',
  'Oppo Find N Fold',
  'OPPO Reno 6 Pro Plus 5G',
  'Oppo Find X5 Pro 5G',
  'OPPO Find N3 Flip',
  'OPPO Reno 9 Z',
  'OPPO Reno8 Lite 5G',
  'Oppo Find X2 Pro AutoMobili Lamborghini Edition',
  'OPPO Reno 4 Pro 5G (12GB RAM + 256GB)',
  'Oppo Find X3 Pro',
  'Oppo K10 Vitality Edition',
  'OPPO Reno 7A',
  'OPPO Find N Flip',
  'OPPO Reno9 Lite 5G',
  'Oppo Reno 8 Pro (8GB RAM + 256GB)',
  'Oppo Reno7 Lite 5G',
  'OPPO A2m',
  'OPPO Reno 8 House of Dragon Edition',
  'OPPO Reno 8 Z',
  'OPPO Reno 6 4G',
  'OPPO Reno 9A',
  'OPPO Find X5 Pro Dimensity Edition',
  'OPPO Reno 9 4G',
  'OPPO Reno8 Pro Plus',
  'Oppo Find X5 5G',
  'Oppo Find N2 5G',
  'OPPO Reno7 Z 5G',
  'OPPO Find N4',
  'OPPO Reno 12 Pro',
  'OPPO A1 Pro 5G',
  'Oppo Find X4 Pro 5G',
  'Oppo Find X5 Lite 5G',
  'OPPO Reno 6',
  'OPPO Reno 6 Pro 5G',
  'Oppo Reno 10x Zoom',
  'OPPO A95 5G',
  'Oppo A93 5G',
  'Oppo Find N 5G',
  'OPPO A91',
  'Oppo Reno6 Pro 5G (Snapdragon)',
  'Oppo Reno 5 Pro Plus 5G',
  'Oppo Reno 4 Lite',
  'Oppo A94 5G',
  'OPPO Find Y',
  'Oppo Reno 10x Zoom (8GB RAM + 256GB)',
  'OPPO Reno 8 Pro House of Dragon Edition',
  'OPPO Find X',
  'OPPO Reno 3 5G Power Edition',
  'Oppo Find X3 Pro Mars Exploration Edition',
  'OPPO N1',
  'Oppo Reno Z',
  'Oppo Reno Ace',
  'Oppo Reno 5G',
  'OPPO Reno 6 Pro 5G Diwali Edition',
  'Oppo Find X3 Lite',
  'OPPO Reno 4 Pro 5G',
  'Oppo Reno 3 Youth',
  'OPPO Reno 4 5G (8GB RAM + 256GB)',
  'Oppo Reno3 Vitality Edition',
  'OPPO Find X2 Lite',
  'OPPO K9 Pro 5G',
  'OPPO Reno',
  'Oppo R15 Pro',
  'OPPO Find 9',
  'Oppo R17 Pro',
  'Oppo K7 5G',
  'Oppo Reno 5 Lite',
  'OPPO Find 5',
  'Oppo Find X3 Neo 5G',
  'OPPO Find X2 Neo',
  'OPPO Reno A',
  'Oppo Find X3',
  'Oppo Reno 10X Zoom FCB Edition',
  'OPPO Reno5 Pro New Year Edition',
  'Oppo N3',
  'Oppo Reno Ace (8GB RAM + 256GB)',
  'OPPO Reno 4 5G',
  'Oppo A72',
  'Oppo Find X Lamborghini Edition'
]
  },

  {
    name: 'VIVO',
   devices : [
  'Vivo X100 Pro Plus',
  'Vivo X100 5G',
  'Vivo X100 Pro 5G',
  'Vivo X90 5G',
  'Vivo X80 Pro 5G',
  'Vivo V40 SE 5G',
  'Vivo V29e',
  'Vivo V30 SE',
  'Vivo X Fold 5G',
  'Vivo X90 Pro 5G',
  'Vivo V26 Pro',
  'Vivo V27e',
  'Vivo X100 Ultra',
  'Vivo S19 Pro',
  'Vivo Y27 5G',
  'Vivo S18',
  'Vivo Y27s',
  'Vivo X Fold 3 Pro',
  'Vivo X110 Pro Plus',
  'Vivo X Fold 3',
  'Vivo X100 5G (16GB RAM + 512GB)',
  'Vivo S17',
  'Vivo S18e',
  'Vivo S19e',
  'Vivo X90 (12GB RAM + 256GB)',
  'Vivo S10 Pro 5G',
  'Vivo V29e (8GB RAM + 256GB)',
  'Vivo Y70',
  'Vivo Y36 5G',
  'Vivo X60 Pro Plus 5G (8GB RAM +128GB)',
  'Vivo S17 Pro',
  'Vivo S19',
  'Vivo X90S',
  'Vivo X Flip 4',
  'Vivo X Fold 5G (12GB RAM + 512GB)',
  'Vivo X Note 5G (12GB RAM + 512GB)',
  'Vivo X90 Pro Plus 5G',
  'Vivo X Flip 3',
  'Vivo S16',
  'Vivo X Flip 2',
  'Vivo S15 Pro 5G',
  'Vivo X Flip',
  'Vivo S17t',
  'Vivo Y36i',
  'Vivo S17e',
  'Vivo S16 Pro',
  'Vivo X Note 5G (12GB RAM + 256GB)',
  'Vivo V21s',
  'Vivo X80T Pro 5G',
  'Vivo X110 Pro',
  'Vivo S16e',
  'Vivo X100S Pro',
  'Vivo T2 4G',
  'Vivo X80 Pro Plus 5G',
  'Vivo X Fold Plus',
  'Vivo X Fold 4',
  'Vivo V28e',
  'Vivo X Note 5G',
  'Vivo Y55s 2023',
  'Vivo S12 Pro 5G',
  'Vivo X60T Pro Plus',
  'Vivo S18 Pro',
  'Vivo V27e 5G',
  'Vivo X70T Pro 5G',
  'Vivo S15E 5G',
  'Vivo S15 5G',
  'Vivo X Fold S',
  'Vivo X110',
  'Vivo X100s',
  'Vivo X50 Pro Plus 5G (12GB RAM + 256GB)',
  'Vivo X Fold 2',
  'Vivo Y55 5G',
  'Vivo Nex 5 5G',
  'Vivo X70 Pro Plus 5G',
  'Vivo X60 Pro',
  'Vivo X70 5G',
  'Vivo X51 5G',
  'Vivo V17 Neo',
  'Vivo Xplay 7',
  'Vivo iQOO Pro',
  'Vivo S12 5G',
  'Vivo X50 Pro 5G',
  'Vivo X50 Pro Plus 5G (8GB RAM + 256GB)',
  'Vivo Nex 3',
  'Vivo X50e 5G',
  'Vivo X60 Pro Plus',
  'Vivo iQOO (12GB RAM + 256GB)',
  'Vivo X30',
  'Vivo Y53s NFC',
  'Vivo Nex 3 5G',
  'Vivo X60T',
  'Vivo S9 5G',
  'Vivo X60s 5G',
  'Vivo Xplay 5 Elite',
  'Vivo X50 Pro Plus 5G',
  'Vivo Nex 3S 5G',
  'Vivo S7 5G',
  'Vivo Xplay 5',
  'Vivo S7T 5G',
  'Vivo iQOO (8GB RAM + 256GB)',
  'Vivo X30 Pro',
  'Vivo iQOO (6GB RAM + 128GB)',
  'Vivo iQOO',
  'Vivo Nex 3 5G (12GB RAM + 256GB)',
  'Vivo X60T Pro 5G'
]
  },

  {
    name: 'Xiaomi',
 devices : [
  'Redmi Note 13 Pro Plus',
  'Redmi Note 15 Pro',
  'Redmi Note 13 Pro Plus (12GB RAM + 512GB)',
  'Redmi Note 13 Pro Plus (12GB RAM + 256GB)',
  'Redmi K70 Pro',
  '14 Ultra',
  '13 Ultra 5G',
  'Redmi Note 13 Pro Max 5G',
  '14 Pro',
  'Redmi Note 14 Pro 5G',
  '14',
  '15 Pro',
  'Redmi Note 12R',
  'Redmi K20 Pro Signature Edition',
  'Redmi K70E',
  'Redmi Note 13 4G',
  'Mix Fold 4',
  '12 Pro 5G (12GB RAM + 256GB)',
  'Redmi Note 12 Turbo Harry Potter Edition',
  'Civi 4',
  'Redmi K70',
  'Mix Fold 2 5G',
  'Mi 10T 5G (8GB RAM + 128GB)',
  'Mi 11 Lite NE 5G',
  'Redmi K80',
  'Civi 3',
  'Mi 11T Pro 5G',
  'Redmi Note 12 Pro Speed Edition',
  'Mix Fold 3',
  'Redmi Note 12S',
  'Mi Mix Fold',
  'Redmi Note 12 Turbo',
  'Mi 11 Lite NE 5G (8GB RAM + 128GB)',
  'Redmi K60 Ultra',
  'Redmi K40 Game Enhanced Edition',
  'Redmi K60E',
  'Redmi Note 12R Pro',
  'Mix Flip',
  'Mi Mix 4',
  '11T Pro 5G (8GB RAM + 256GB)',
  'Redmi Note 10 Pro 5G',
  'Redmi K50 Pro 5G',
  '12 Pro 5G',
  'Civi 2',
  '13T',
  '12T',
  'Redmi K60 Pro',
  'Redmi Note 11T Pro 5G',
  'Redmi Note 11E Pro 5G',
  'Mix 5 Pro 5G',
  'Redmi K60 Gaming Edition',
  'Redmi K50s Pro 5G',
  '12S Pro 5G',
  'Redmi K50 Pro Plus 5G',
  'Redmi K40 Light Luxury Edition',
  'Redmi Note 11T Pro Plus 5G',
  '11 LE 5G',
  'Redmi K50 Extreme Edition',
  'Redmi K60',
  'Civi 3 Disney Limited Edition',
  'Redmi Note 13R Pro',
  'Redmi K80 Pro',
  '15',
  'Redmi Note 12T Pro',
  '12S Ultra',
  '12 Lite 5G',
  'Redmi Note 11S 5G',
  'Redmi K50 5G',
  'Redmi K50 Ultra 5G',
  'Redmi Note 13 Pro 4G',
  'Redmi Note 12 Explorer',
  '13 Lite',
  'Mi 12 5G',
  'Civi 2S',
  'Redmi Note 12 Discovery Edition',
  'Redmi 10 5G',
  '13 5G',
  'Redmi 13R 5G',
  '12 Lite Ne 5G',
  '12 Lite Zoom 5G',
  '13T Pro 5G',
  'Civi 1S 5G',
  '12T Pro 5G',
  'Mi 10T 5G',
  'Redmi K50 Gaming Edition',
  '12 Ultra 5G',
  'Mi 10T Pro 5G',
  '12S 5G',
  '12 Pro Dimensity Edition',
  'Redmi Note 12 Pro 4G',
  'Mi Mix 5',
  'Redmi K70 Ultra',
  'Redmi K60 Prime',
  '13 Pro 5G',
  '12 Mini',
  'Mi 10 Ultra',
  'Mi 10 5G (8GB RAM + 256GB)',
  'Redmi K20 Pro Exclusive Edition',
  'Mi 9 Pro 5G',
  'Mi 11',
  'Mi3 (16GB)',
  'Mi 11 Pro',
  'Mi CC9 Meitu Edition',
  'Mi Mix 3 5G',
  'Redmi K30 Pro',
  'Redmi K40 Gaming Lite',
  'Redmi Note 8T',
  'Mi 8 (6GB RAM + 128GB)',
  'Mi Mix 2s',
  'Mi Note 10 Lite',
  'Redmi K30S Ultra',
  'Redmi K40 Pro',
  'Mi Note 10 Lite (8GB RAM + 128GB)',
  'Mi Mix 2s (6GB RAM + 64GB)',
  'Mi3 (64GB)',
  'Mi 9 (6GB RAM + 128GB)',
  'Mi 9T Pro',
  'Mi 10 Lite 5G',
  'Mi Mix',
  'Mi 9S',
  'Mi 6',
  'Redmi K30',
  'Mix Evo',
  'Redmi K30 5G (8GB RAM +128GB)',
  'Mi 8',
  'Mi Note 10 Pro',
  'Redmi 9T',
  'Redmi K40 Pro Plus',
  'Mi 9T (6GB RAM + 128GB)',
  'Mi 9 SE (6GB RAM + 128GB)',
  'Mi 2A',
  'Mi 9 Explorer',
  'Mi 5s Plus',
  'Redmi 10X Pro 5G (8GB RAM + 256GB)',
  'Mi 10 Youth Edition 5G (8GB RAM + 128GB)',
  'Mi 9X',
  'Mi Mix 2 Special Edition',
  'Redmi K30i 5G',
  'Mi Note 10',
  'Mi 9 (6GB RAM+64GB)',
  'Redmi K40 Pro',
  'Redmi Note 8T (4GB RAM + 128GB)',
  'Mi 8 (8GB RAM + 128GB)',
  'Mi Note 3 (6GB RAM + 64GB)',
  'Mi 9',
  'Mi Note 2',
  'Mi 10 Lite 5G',
  'Redmi Pro 2',
  'Mi 6',
  'Mi CC9',
  'Mi5 Plus',
  'Redmi K20 Pro Marvel Edition',
  'Mi 8',
  'Mi 8 (6GB RAM + 256GB)',
  'Civi 5G',
  'Mi CC9 Pro (8GB RAM +128GB)',
  'Mi 10 Lite Zoom Edition',
  'Mi 10 Youth Edition 5G',
  'Mi 8 Pro',
  'Mi 9 SE',
  'Mi 11T 5G',
  'Mi Mix 3 (8GB RAM + 256GB)',
  'Mi 9 Pro',
  'Mi Mix 2',
  'Mi CC9 Pro',
  'Mi 6 2021',
  'Redmi K30 5G',
  'Mi 9 Lite',
  'Mi 9T',
  'Mi 10 Youth Edition 5G (6GB RAM + 128GB)',
  'Redmi K30 Ultra',
  'Mi S',
  'Mi 5s',
  'Mi 7',
  'Redmi K30 5G Racing Edition',
  'Mi 11 Ultra',
  'Mi Note 2 Special Edition',
  'Redmi K40',
  'Mi 8 Pro (6GB RAM + 128GB)',
  'Redmi Note 9 Pro 5G',
  'Mi Note 3 (4GB RAM + 64GB)',
  'Redmi K30i 5G (8GB RAM + 256GB)',
  'Redmi Note 9T 5G',
  'Mi 8 Explorer Edition',
  'Redmi K30 Pro Zoom Edition',
  'Mi Mix 3 (8GB RAM + 128GB)',
  'Mi Mix 3 (10GB RAM + 512GB)',
  'Mi 10 Pro Plus',
  'Mi 10T Lite 5G',
  'Redmi 10X Pro 5G',
  'Mi 11 Lite 5G',
  'Mi 6 Plus',
  'Redmi K30S',
  'Mi Mix 2s (6GB RAM + 128GB)',
  'Mi Mix 3',
  'Redmi Note 8T (4GB RAM + 64GB)',
  'Redmi K40s 5G',
  'Mi 5',
  'Mi Mix 2 (6GB RAM + 64GB)',
  'Mi Note 3',
  'Redmi 9C NFC',
  '11T Pro 5G (12GB RAM + 256GB)',
  'Mi 10 Pro',
  'Mi 10 5G',
  'Redmi K30 (8GB RAM +128GB)'
]
  }
];

  constructor(private websiteSeoSyncService: WebsiteSeoSyncService) { }

  ngOnInit() {
    this.websiteSeoSyncService.applySeoByPageName('nfc-compatible-devices');
  }




toggleBrand(brandName: string): void {
  if (this.openedBrand === brandName) {
    this.openedBrand = null;
  } else {
    this.openedBrand = brandName;
  }
}
}

